#' @import utils  
utils::globalVariables(c("...",
                         ":=",
                         ".",
                         ".full",
                         "Included_final",
                         "grup",
                         "grup1",
                         "grup2",
                         "iris",
                         "dades",
                         "crit_temp",
                         "filtres",
                         "camp",
                         "tipus_cri",
                         "dumy",
                         "filtre_tipus",
                         "suma_n",
                         "criteri",
                         "etiqueta_exclusio"))

